base_url = "https://architecture.yarosh.dev"
title = ""
description = ""
author = "Yuriy Yarosh <yuriy@yarosh.dev>"

default_language = "en"

compile_sass = false
build_search_index = true
generate_sitemap = true
generate_robots_txt = true
minify_html = false
taxonomies = [{ name = "tags" }]

[markdown]
highlight_code = true
error_on_missing_highlight = true
render_emoji = true
smart_punctuation = true
definition_list = true
lazy_async_image = true
insert_anchor_links = "heading"

extra_syntaxes_and_themes = []
highlight_theme = "base16-ocean-dark"

external_links_no_referrer = true
external_links_no_follow = true

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"
paths_keep_dates = false

[search]
index_format = "fuse_javascript"

[languages]

# [languages.uk]
# title = "RCNA"
# description = ""

# [languages.pl]
# title = "RCNA"
# description = ""

# [languages.cz]
# title = "RCNA"
# description = ""

# [languages.de]
# title = "RCNA"
# description = ""

# [languages.fr]
# title = "RCNA"
# description = ""

# [languages.it]
# title = "RCNA"
# description = ""

# [languages.es]
# title = "RCNA"
# description = ""

[extra]
google_site_verification = ""
